### ISSUE TITLE
Apple generates outside canvas

### ISSUE THREAD

**Issue by ojaswa1942** [SivaramPg/JS_Snake_Game#7]
If you keep refreshing the page, or after restarting the game by pressing escape..On continuous occurrences, once in a while, apple is generated outside the canvas.
Please check calculations since display has been modified to solve previous bug.
You'll be able to see the problem after merge.

**Comment by SivaramPg** [comment]
I have fixed this by using canvas.width and canvas.height to calculate the apple.
This has fixed the issue of apple going off canvas.
Since we added header and footer into the window, the canvas shrunk but snake and apple were still using the larger window.width and window.height methods so they would not sometimes fit in the canvas and overflow to either the header or footer!
